### ISSUE TITLE
Any chance that you could compile this for Android 5.1?

### ISSUE THREAD

**Issue by rbreaves** [dhylands/ueventmon#1]
I don't have a dev environment set up atm to do something like that and if it wouldn't be too much trouble I would greatly appreciate it.

**Comment by rbreaves** [comment]
Closing this, found other ways to capture what I needed.

https://github.com/Cartucho/android-touch-record-replay
https://qatesttech.wordpress.com/2012/06/21/turning-the-output-from-getevent-into-something-something-that-can-be-used/

**Comment by davehylands** [comment]
I was going to say that I don't have anything set up for that either. It's been quite a few years since I've been working in this space.
